services:
  # 1. The PX4 & Gazebo Simulation
  px4-sim:
    build:
      context: .
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    container_name: atmos_sim
    network_mode: host
    ipc: host
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    user: "${UID:-1000}:${GID:-1000}"
    group_add:
      - dialout
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - XAUTHORITY=/home/developer/.Xauthority
      - QT_X11_NO_MITSHM=1
      - HEADLESS=${HEADLESS:-0}
      - NS=quadrotor
    volumes:
      # Mounts the X11 socket for Gazebo GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/developer/.Xauthority:ro
      - ./workspace/:/workspace
    # Launches the simulation and QGC
    command:
      - -lic
      - |
        MicroXRCEAgent udp4 -p 8888 > /workspace/MicroXRCEAgent_logs.txt 2>&1 &
        /qgc/QGroundControl-x86_64.AppImage --appimage-extract-and-run > /workspace/QGC_logs.txt 2>&1 &
        ros2 launch px4_mpc mpc_spacecraft_launch.py > /workspace/mpc_logs.txt 2>&1 &
        cd /PX4-Autopilot && HEADLESS=$HEADLESS make px4_sitl_spacecraft gz_atmos
